### ISSUE TITLE
Not working from `init()` method

### ISSUE THREAD

**Issue by xmlking** [markbates/pkger#27]
After generating  `pkged.go`, I was hoping I can run the same way without `public` folder. but it is failing...

Sample code to reproduce...

[pkger-example.zip](https://github.com/markbates/pkger/files/3829863/pkger-example.zip)

Before renaming `public`
```
go run main.go pkged.go
in shared init
Name:  index.html
Size:  257
Mode:  -rw-rw-r--
ModTime:  2019-11-10 15:59:20 -0800 PST
in main init
hi
Name:  index.html
Size:  257
Mode:  -rw-rw-r--
ModTime:  2019-11-10 15:59:20 -0800 PST
```

After renaming `public` to `public1`
```
go run main.go pkged.go
in shared init
2019/11/10 22:04:25 stat /mywork/pkger-example/public/index.html: no such file or directory
exit status
```

**Comment by xmlking** [comment]
main.go
```go
package main

import (
	"fmt"
	"log"

	"app/shared"
	"github.com/markbates/pkger"
)



func main() {
	println("in main init")
	shared.Say()
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	info, err := pkger.Stat("/public/index.html")
	if err != nil {
		return err
	}

	fmt.Println("Name: ", info.Name())
	fmt.Println("Size: ", info.Size())
	fmt.Println("Mode: ", info.Mode())
	fmt.Println("ModTime: ", info.ModTime())

	return nil
}
```
config.go
```go
package shared

import (
	"fmt"
	"log"

	"github.com/markbates/pkger"
)

func init() {
	println("in shared init")
	info, err := pkger.Stat("/public/index.html")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println("Name: ", info.Name())
	fmt.Println("Size: ", info.Size())
	fmt.Println("Mode: ", info.Mode())
	fmt.Println("ModTime: ", info.ModTime())
}

func Say() {
	println("hi")
}


```

**Comment by aperezg** [comment]
If you look inside the `pkged.go` created, you could see that a `_` var is created calling to the `Apply` method. The `Apply` method is in charge of the magic to read the binary files.

But if you use a init for this read files you will have a unexpected results, because the package import sort matters.

I try to illustrate with this simple code:
https://play.golang.org/p/vy40L7ogbWD

I think that read files from init() is a not good idea, with this package or another, you could the same with an explicit call.

**Comment by xmlking** [comment]
it is common to load config files in `init()` bootstrap dependencies.  it would be nice if we have explicit way to call `Apply` in `pkged.go` sothat we carol the order

**Comment by markbates** [comment]
https://medium.com/@markbates/go-init-order-dafa89fcef22

The `init` function is unpredictable, and can cause a lot of problems. It is generally frowned upon to use because of that. It caused many, many issues in Packr, that I'm not excited about repeating with pkger. 

To that end, I have a couple of potential solutions to the problem.

1) would be for you to roll your own, instead of using the `pkger` command itself. https://github.com/markbates/pkger/blob/1a3cb0f04d44d7670f56127bb574eb30b97b3867/cmd/pkger/cmds/pack.go#L113 It's not particularly difficult, but I can understand that might not be desirable.

2) a `-template` flag that allows you to pass in your own template instead of the one that pkger uses by default. I prefer this solution, as it helps other peeps too.

**Comment by xmlking** [comment]
the second option would be nice, so that we can have our own wrapper function and control when and where   `pkger` get initialized.

**Comment by nlepage** [comment]
I have a use case where I want to add build tags to `pkged.go`, which could also be solved by a `-template` flag.

**Comment by diamondburned** [comment]
> The init function is unpredictable, and can cause a lot of problems. It is generally frowned upon to use because of that. It caused many, many issues in Packr, that I'm not excited about repeating with pkger.

Why not run it in a variable?

```go
var _ = func() {
    log.Println("Free init!")
}()
```

**Comment by rusq** [comment]
For the benefit of others, can this information (not working when initialised through `init`) at least be included in the README.md?

Spent couple of hours trying to figure out why the trivial set up did not work, had initialised templates in init() function in the subpackage, it worked fine with the directory present, and packaged ok, but when executable file was moved elsewhere, it could not access virtual template directory and failed.  Once everything moved to New() (and out of init), everything started working.

**Comment by markbates** [comment]
PRs are welcome, especially for docs.
